NVIDIA/numbast

ast_canopy/cpp/include/ast_canopy.hpp
This PR removes the stale `parse_declaration_from_ast` header, implementations are removed in an earlier PR, but I forgot to remove the declaration in that PR.﻿
=> Remove stale API decl

.github/workflows/pr.yaml
Currently "legacy_test" and "frontier_test" runs in parallel of style checks job in CI.
In theory test jobs should not run at all if the PR doesn't pass style checks.﻿
=> CI tests depends on style checks

ast_canopy/ast_canopy/api.py, ast_canopy/ast_canopy/pylibastcanopy.cpp, ast_canopy/ast_canopy/pylibastcanopy.pyi, ast_canopy/cpp/include/ast_canopy.hpp, ast_canopy/cpp/src/field.cpp, ast_canopy/cpp/src/record.cpp, ast_canopy/tests/data/sample_access_specifier.cu, ast_canopy/tests/test_parse_from_source.py, numbast/src/numbast/struct.py, numbast/tests/data/sample_struct.cuh, numbast/tests/test_struct.py
This PR fixes a bug in Numbast. AST_canopy currently do not parse private fields of structs,
originally this was meant for not creating bindings for non-public attribute / methods of
C++ structs. However, Numbast still needs these information to create the proper LLVM types
during lowering, so that when moving the object around, proper IR with type is emit. This PR
adds back those information, but attaching access specifier information to each field. Numbast
create bindings based on access specifier information, and uses all field information to lower
it to proper LLVM type.
﻿- Parse all fields, and add access specifier information
- update pylibastcanopy stub
- patch numbast to properly generate llvm types for struct models
=> Fix Bug: Numbast do not create proper llvm structure type when lowering struct with private / protected fields

ast_canopy/tests/data/sample_access_specifier.cu, ast_canopy/tests/data/sample_class_template.cu, ast_canopy/tests/data/sample_diff_by_cc.cu, ast_canopy/tests/data/sample_enum.cu, ast_canopy/tests/data/sample_execution_space.cu, ast_canopy/tests/data/sample_function.cu, ast_canopy/tests/data/sample_function_template.cu, ast_canopy/tests/data/sample_nested_struct.cu, ast_canopy/tests/data/sample_struct.cu, ast_canopy/tests/data/sample_typedef.cu
This PR adds the missing copyright headers for all sample data used in tests﻿
=> Insert Copyright in all Sample Data

ci/setup_build_test.sh, conda/environment.yaml, conda/environment_template.yaml
As pointed out by Vyas, `cuda-toolkit` is a meta package that does not depend on `cuda-version`. Components of `cuda-toolkit` may depend on `cuda-version`, which previously I relied on that dependency to get the correct CTK components. Some unexpected CI [**success**](https://github.com/NVIDIA/numbast/actions/runs/8897777445/job/24433476729#step:5:443) has shown that the default compiler in CI environment mismatches that defined for `cuda-version`, indicating a transitive dependency failure. Therefore, this PR explicitly pins `cuda-toolkit` package version.
=> Pin `cuda-toolkit` version for dependencies

numbast/benchmarks/test_rtc.py, numbast/src/numbast/function.py, numbast/src/numbast/struct.py
This PR moves shim function generation to lowering time, this limits the shim functions to only
those used in kernels. Expected to reduce I/O and RTC time.
This PR also adds a simulated occasion to generate N functions for Numbast to benchmark optimization. The benchmark shows that with ~100 function declarations, this PR reduces the best case kernel launch time time by 40%
Closes ﻿#15
Benchmark data
`bench-a` is this branch, `bench-m` is main.
```
------------------------------------------------------------------------------- benchmark 'test_rtc[1000]': 2 tests --------------------------------------------------------------------------------
Name (time in ms)                      Min                 Max                Mean            StdDev              Median               IQR …
```
=> Generate shim functions at lowering time

.github/workflows/conda-python-build.yaml
This PR fixes a bug introduced in #58. Where the conda package test script is `test_conda.sh`, not `run_test.sh﻿`
=> bug fix: conda build workflow uses the wrong test script

numbast/README.md
This PR adds readme to the Numbast module. Which is previously missing.
=> Add readme to numbast module

ast_canopy/cpp/src/ast_canopy.cpp
`unique_ptr`'s raw pointer constructor is explicit, so copy initialization will fail. See: C++ Standard [unique.ptr.single.ctor] https://eel.is/c++draft/unique.ptr.single.ctor#lib:unique_ptr,constructor_
Example of the issue: https://godbolt.org/z/3WrEY18T8
This happens with older versions of the Clang library, where `ASTUnit::LoadFromCommandLine` returns an `ASTUnit*` instead of a `unique_ptr<ASTUnit>`. 
https://github.com/NVIDIA/numbast/blob/main/ast_canopy/cpp/src/ast_canopy.cpp#L65-L66
I ran into this with Clang 16. In the latest versions of the Clang library, it does return a `unique_ptr`, so there's no issue.
https://clang.llvm.org/doxygen/classclang_1_1ASTUnit.html#a10bdfe1735fbb62b6c43decedb22c333
Direct initialization works fine for both versions.
=> Replace invalid `unique_ptr` copy initialization from a raw pointer with direct initialization

numbast/src/numbast/static/types.py, numbast/src/numbast/tools/static_binding_generator.py
Fixes 2 bugs as the title suggests.
=> Fixes bug where `types.void` is cast to `none` string and where static_binding_generator parses a None type from yaml

numbast/src/numbast/function.py, numbast/src/numbast/static/function.py
Numbast only parses device side functions, host side functions are currently skipped in silence. This PR adds a warning so that users gets an early warning.
=> Raise Warning when Numbast Skips a Non-Device Function

ast_canopy/ast_canopy/api.py, ast_canopy/tests/data/noinline_macro_fix.cu, ast_canopy/tests/test_noinline_fix.py
This PR puts the default C++ header extraction command into clang++ cuda mode. This ensures that some patches for CUDA headers made by upstream clang are included.
=> Fix clang++ default header extraction command

conda/recipes/ast_canopy/meta.yaml, numbast/src/numbast/static/struct.py, numbast/src/numbast/static/tests/test_struct_static_bindings.py
The use of `isinstance` is a static type check at compile time. Adding `as_numba_type` helps Numba resolving the python struct handle to the newly created Numba type. As is shown here: https://numba.readthedocs.io/en/stable/reference/types.html?highlight=as_numba_type#numba.extending.as_numba_type
=> Add Support to `isinstance` Type Check to New Types

.github/workflows/publish.yaml
We have two jobs in publish workflow currently. Each build to the same set of targets: `py3.10-3.13` x `aarch64/amd64`. As it turns out that the `CPU` field has no effect to the build. If we run the publish job, it builds the same targets twic. On upload, it runs into duplicate artifact conflicts: https://github.com/NVIDIA/numbast/actions/runs/14845380294/job/41677954654.
This PR removes one of the job and only use the amd64 instance to build for all targets.
=> Use Single Upload Job for CondaBuild

ast_canopy/cpp/CMakeLists.txt, ast_canopy/cpp/src/ast_canopy.cpp, ast_canopy/cpp/src/detail/matchers.hpp, ast_canopy/cpp/src/detail/matchers/class_template_partial_specialization_matcher.cpp, ast_canopy/cpp/src/detail/matchers/record_matcher.cpp, ast_canopy/tests/data/sample_ctpsd.cu, ast_canopy/tests/test_ctpsd.py
Due to an upstream ASTMatcher bug: 
https://github.com/llvm/llvm-project/issues/138782#issuecomment-2856591256
We cannot reliably skip matching nested `RecordDecl` inside a `ClassTemplateParitialSpecializationDecl` node. And since invoking `getTypeSize` on an uninstantiated record is generally a bad idea, (in fact, it leads to infinite recursion currently). We use a WAR to skip parsing any nested `RecordDecl` that exists inside a `CTPSD` node. It works like this:
Make a CTPSD matcher that precedes all existing matcher. When we matched a CTPSD node, use a separate `RecursiveASTVisitor` to traverse this node and collect all `RecordDecl` from within. Memoize all `RecordDecl` ID in the payload. When the matcher matches a `RecordDecl`, check if its ID is within the memoization. If it is, skip …
=> Add CTPSD matcher, WAR nested `RecordDecl`

numbast/src/numbast/tools/static_binding_generator.py, numbast/src/numbast/tools/tests/config/output_name.yml.j2, numbast/src/numbast/tools/tests/conftest.py, numbast/src/numbast/tools/tests/test_output_name.py
This PR adds `Output Name` Field to configuration, that allows custom name for the generated binding file.
=> Allow Custom Binding Name Specified via YAML

numbast/src/numbast/static/function.py, numbast/src/numbast/tools/static_binding_generator.py, numbast/src/numbast/tools/tests/config/cooperative_launch.yml.j2, numbast/src/numbast/tools/tests/conftest.py, numbast/src/numbast/tools/tests/test_use_cooperative.py, numbast/src/numbast/tools/tests/use_cooperative.cuh
This PR adds config: `Cooperative Launch Required APIs`, a list of strings that specify the names of the function that requires cooperative launch.
=> Add config for functions that requires cooperative launch

numbast/src/numbast/static/function.py, numbast/src/numbast/tools/static_binding_generator.py, numbast/src/numbast/tools/tests/config/cooperative_launch.yml.j2, numbast/src/numbast/tools/tests/config/cooperative_launch_invalid_regex.yml.j2, numbast/src/numbast/tools/tests/config/cooperative_launch_regex.yml.j2, numbast/src/numbast/tools/tests/conftest.py, numbast/src/numbast/tools/tests/test_use_cooperative.py, numbast/src/numbast/tools/tests/use_cooperative.cuh, numbast/src/numbast/tools/yaml_tags.py
In #133 we introduced a list of function names that specifies bindings that requires cooperative launch. In certain uses cases this list can grow too large (parameterized function names such as `[TYPENAME]_sync` where TYPENAME can grow beyond 20 types). A regex is more succinct in representing these requirements.
=> Alter cooperative launch list to regex list

numbast/src/numbast/errors.py, numbast/src/numbast/static/function.py, numbast/src/numbast/static/struct.py, numbast/src/numbast/static/tests/data/conflict_func_name_1.cuh, numbast/src/numbast/static/tests/data/conflict_func_name_2.cuh, numbast/src/numbast/static/tests/data/multiple_decls.cuh, numbast/src/numbast/static/tests/test_multiple_decls.py
This PR makes use of the `mangled_name` attribute added in #139 to remove duplicate declarations due to forward declarations in C++.
Currently, because we use a crude manner to track the number of bindings created for each function, there can be duplicates if multiple forward declarations are found from the code base. This is not ideal as it bloats the binding file size. This PR make uses of mangled name, which *uniquely distinguishes* functions that have the same function signature in the same scope, effectively removing duplicate bindings created for forward declarations.
=> Use function mangled name to deduplicate forward declared function decls

numbast/src/numbast/static/function.py, numbast/src/numbast/tools/static_binding_generator.py, numbast/src/numbast/tools/tests/config/prefix_removal.yml.j2, numbast/src/numbast/tools/tests/prefix_removal.cuh, numbast/src/numbast/tools/tests/test_prefix_removal.py
This PR adds a prefix remover item to config file. Any prefix specified in this list will be removed from the generated bindings for functions.
Note this is for function only, support for record maybe added in the future should there be a RFE.
=> Add Prefix Remover for Functions in Static Binding Generator

ast_canopy/cpp/src/function.cpp, ast_canopy/tests/data/sample_itanium_mangled_names.cu, ast_canopy/tests/test_mangled_name.py, conda/environment.yaml, conda/environment_template.yaml, conda/recipes/ast_canopy/meta.yaml
In #145 we bumped the clangdev version to 19, which originally was thought to be a solution to a segfault to the name mangling on a `CXXConstructorDecl` node. However, later troubleshooting shows that the issue is caused by the `GlobalDecl` node is constructed with the wrong constructor. When creating a `GlobalDecl` from a ctor decl node, it should explicitly specify the `CXXCtorType` in argument. In our most common use case, we use `Ctor_Complete` for most cases.
This PR reverts the minimum clangdev pinning back to 18 as it turns out to be irrelevant to the cause of crash.
=> Fix a Bug where GlobalDecl is constructed mistakenly when performing name mangles

ast_canopy/ast_canopy/api.py, ast_canopy/cpp/src/ast_canopy.cpp, numbast/src/numbast/static/tests/conftest.py, numbast/src/numbast/tools/static_binding_generator.py, numbast/src/numbast/tools/tests/config/cc.yml.j2, numbast/src/numbast/tools/tests/config/cfg.yml.j2, numbast/src/numbast/tools/tests/config/cooperative_launch.yml.j2, numbast/src/numbast/tools/tests/config/cooperative_launch_invalid_regex.yml.j2, numbast/src/numbast/tools/tests/config/cooperative_launch_regex.yml.j2, numbast/src/numbast/tools/tests/config/module_callbacks.yml.j2, numbast/src/numbast/tools/tests/config/output_name.yml.j2, numbast/src/numbast/tools/tests/config/predefined_macros.yml.j2, numbast/src/numbast/tools/tests/config/prefix_removal.yml.j2, numbast/src/numbast/tools/tests/config/require_pynvjitlink.yml.j2, numbast/src/numbast/tools/tests/config/shim_include_override.yml.j2, numbast/src/numbast/tools/tests/conftest.py, numbast/src/numbast/tools/tests/test_additional_includes.py, numbast/src/numbast/tools/tests/test_cc.py, numbast/src/numbast/tools/tests/test_cli.py, numbast/src/numbast/tools/tests/test_macros.py, numbast/src/numbast/tools/tests/test_module_callbacks.py, numbast/src/numbast/tools/tests/test_output_name.py, numbast/src/numbast/tools/tests/test_predefined_macros.py, numbast/src/numbast/tools/tests/test_prefix_removal.py, numbast/src/numbast/tools/tests/test_repro_info.py, numbast/src/numbast/tools/tests/test_require_pynvjitlink.py, numbast/src/numbast/tools/tests/test_shim_include_override.py, numbast/src/numbast/tools/tests/test_symbol_exposure.py, numbast/src/numbast/tools/tests/test_use_cooperative.py
This PR adds `GPU Arch` entry in the yaml config file to specify the CC to generate for strings. Note that currently we only support generating for a single GPU arch, though multiple targets are meant to be a future PR.
=> Configure static binding CC via `GPU Arch` Entry

numbast/src/numbast/static/function.py, numbast/src/numbast/static/renderer.py, numbast/src/numbast/static/struct.py, numbast/src/numbast/static/tests/conftest.py, numbast/src/numbast/static/tests/test_enum_static_bindings.py, numbast/src/numbast/static/tests/test_function_static_bindings.py, numbast/src/numbast/static/tests/test_link_two_files.py, numbast/src/numbast/static/tests/test_operator_bindings.py, numbast/src/numbast/static/tests/test_static_demo.py, numbast/src/numbast/static/tests/test_struct_static_bindings.py, numbast/src/numbast/tools/static_binding_generator.py, numbast/src/numbast/tools/tests/config/use_separate_registry.yml.j2, numbast/src/numbast/tools/tests/test_use_separate_registry.py
In Numba-CUDA's fp16 bindings, we have separate introduction of typing and target registries. This PR automates that within the Numbast pipeline with `Use Separate Registries` entry to control that.
=> Allow creation of custom typing/target registry

ast_canopy/ast_canopy/api.py
This is also clang's default c++ standard.
=> Use GNU Extension Standard for Default Clang Parse

ast_canopy/build.sh
In conda environment with cmake package, `CMAKE_PREFIX_PATH` is a preset variable. We don't need to set this in the build script.
However, `CMAKE_INSTALL_PREFIX` is not set, so we apply the conda environment detection manually.
=> Set CMAKE_INSTALL_PREFIX in conda environment

ast_canopy/CMakeLists.txt, ast_canopy/build.sh
In https://github.com/NVIDIA/numbast/pull/188 `build.sh` we captured `CMAKE_PREFIX_PATH` *from environment* and pass it to astcanopy build options. The argument specified in the docstring says that it is a "semicolon separated list". This contradicts with cmake standard where environment variable are "colon separated list", while cmake options arguments are "semicolon separated list". Additionally `ASTCANOPY_INSTALL_PATH` is concatenated to `CMAKE_PREFIX_PATH` with semi-colon delimiter, further violating the convention.
This caused a bug where the downstream skbuild for pylibastcanopy picked up the wrongly delimited list and failed to search the install path of astcanopy.
This PR is a temporary fix for this issue. It implements two normalizer, and uniformly converts the list into:
- colon …
=> Propagate CMAKE_PREFIX_PATH from environment variable properly to skbuild
